const { NEWCOMER_DAYS } = require('../config/constants');

function buildHelpLines() {
    return [
        '## Bot使い方マニュアル',
        '',
        'このBotは、フォーラム通知、ロールメンション転載、自動リアクション、ロール確認、Webhook転送などを行えます。',
        '管理系コマンドは、基本的にサーバー管理権限を持つ人向けです。',
        '',
        '---',
        '',
        '## /forum',
        'フォーラムに新しいスレッドが作成されたとき、指定したチャンネルまたはスレッドへ通知します。',
        '',
        '### /forum channel',
        'フォーラム通知設定を追加します。',
        '`/forum channel target_channel:#通知先 forum:#フォーラム`',
        '`/forum channel target_channel:#通知先 forum_ids:123,456,789`',
        '`/forum channel target_channel:#通知先 forum:#フォーラム message:{forum} に、新しいスレッドが作成されました！\\nスレ主: {author}{newcomerMark}\\nリンク: [{thread}]({link})`',
        '',
        '### /forum show',
        '現在のフォーラム通知設定を表示します。消えている通知先は一括削除または個別削除できます。',
        '',
        '### /forum unset',
        'フォーラム通知設定を削除します。forum だけ、target_channel だけの指定もできます。',
        '',
        '### /forum placeholders',
        'フォーラム通知メッセージで使えるプレースホルダ一覧を表示します。',
        `ご新規さん判定は、サーバー参加から ${NEWCOMER_DAYS} 日以内です。`,
        '',
        '---',
        '',
        '## /rolemention',
        '特定ロールがメンションされた投稿を、別チャンネルまたはスレッドへ転載します。',
        '`/rolemention set role:@対象ロール target_channel:#転載先`',
        '`/rolemention set role:@対象ロール target_channel:#転載先 message:送信主：{author}\\n{body_quote}\\n{link}`',
        '`/rolemention show` / `/rolemention unset role:@対象ロール` / `/rolemention placeholders`',
        '',
        '---',
        '',
        '## /reaction',
        '指定チャンネルで、指定ユーザーの投稿に自動リアクションを付けます。',
        '`/reaction set target_channel:#対象チャンネル user:@対象ユーザー emoji:✅`',
        '`/reaction show` / `/reaction unset target_channel:#対象チャンネル user:@対象ユーザー`',
        'Bot投稿にも反応させたい場合は `/reaction allowbot add user:@Bot` を使います。',
        '',
        '---',
        '',
        '## /forward',
        'Webhookを使って、投稿を別チャンネルや別サーバーへ転送します。',
        'source_channel を指定しない場合、そのサーバー全体の投稿が転送対象になります。',
        '',
        '特定チャンネルだけ転送:',
        '`/forward set target_webhook_url:https://discord.com/api/webhooks/... source_channel:#転送元`',
        '',
        'サーバー全体を転送:',
        '`/forward set target_webhook_url:https://discord.com/api/webhooks/...`',
        '',
        '除外チャンネル:',
        '`/forward exclude add channel:#除外したいチャンネル`',
        '`/forward exclude show`',
        '`/forward exclude remove channel:#除外解除したいチャンネル`',
        '',
        'Bot/Webhook投稿の転送許可:',
        '`/forward allow add type:bot id:123456789012345678`',
        '`/forward allow add type:webhook id:123456789012345678 source_channel:#転送元`',
        '',
        '転送仕様:',
        '・人間の投稿はそのまま転送対象になります。',
        '・Bot投稿は許可Bot、Webhook投稿は許可Webhookに登録されている場合だけ転送します。',
        '・転送本文の最後に元投稿へのリンクを追加します。',
        '・ご新規さんの場合、転送先の投稿者名の先頭に 🔰 が付きます。',
        '・カスタム絵文字は可能な範囲で転送先でも表示できる形式に変換します。',
        '',
        '---',
        '',
        '## /role',
        'ロール条件でメンバー一覧やコピペ用メンションを表示します。',
        '`/role missing list role:@対象ロール`',
        '`/role missing mention role:@対象ロール`',
        '`/role channelnever list role:@対象ロール source_channel:#確認チャンネル`',
        '`/role channelnever mention role:@対象ロール source_channel:#確認チャンネル`',
        '`/role filter list has:@持っているロール not:@持っていないロール`',
        '`/role filter mention has:@持っているロール not:@持っていないロール`',
        '',
        '---',
        '',
        '## /hasrole',
        '指定したロールを持っているメンバー一覧を表示します。',
        '`/hasrole list role:@対象ロール`',
        '',
        '---',
        '',
        '## /joined',
        '自分がこのサーバーに参加してからの日数を表示します。',
        'このコマンドは管理権限がなくても誰でも使用できます。',
        '`/joined`',
        '',
        '---',
        '',
        '## 注意',
        '・Webhook URLは秘密情報です。公開チャンネルやGitHubなどに貼らないでください。',
        '・転送ループを防ぐため、このBot自身の投稿は転送しません。',
        '・サーバー全体転送を使う場合、不要なチャンネルは `/forward exclude add` で除外してください。',
        '・VC内チャットは環境や権限によって取得できない場合があります。',
    ];
}

module.exports = {
    buildHelpLines,
};
